# Generated by Django 5.0.1 on 2024-02-09 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waterapp', '0005_alter_products_total_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='addtocart',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='waterapp.addcompany'),
        ),
    ]
