# Generated by Django 5.0.1 on 2024-02-09 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('waterapp', '0006_addtocart_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addtocart',
            name='name',
        ),
    ]
