# Generated by Django 5.0.1 on 2024-02-07 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waterapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyname', models.CharField(max_length=50, null=True)),
                ('logo', models.ImageField(null=True, upload_to='')),
            ],
        ),
    ]
