# Generated by Django 5.0.1 on 2024-02-07 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waterapp', '0002_addcompany'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=20, null=True)),
                ('price', models.CharField(max_length=25, null=True)),
                ('image', models.ImageField(null=True, upload_to='')),
                ('companyname', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='waterapp.addcompany')),
            ],
        ),
    ]
