# Generated by Django 5.0.1 on 2024-02-08 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waterapp', '0004_products_total_quantity_addtocart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='total_quantity',
            field=models.CharField(max_length=5000),
        ),
    ]
